"use client";

import { useState } from "react";
import { motion } from "framer-motion";
import Link from "next/link";
import {
  Sparkles,
  Calendar,
  DollarSign,
  CheckSquare,
  ArrowRight,
  Zap,
  Shield,
  Globe,
  Loader2,
  MessageSquare,
  Receipt,
  Brain,
  RefreshCcw,
  Search,
  Github,
  Twitter,
  Mail,
  Sun,
  Moon,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { getGoogleLoginUrl } from "@/lib/api";
import { toast } from "sonner";
import { useTheme } from "next-themes";

/* ─────────────────────────────────────────── data ─ */
const features = [
  {
    icon: Calendar,
    title: "Daily Briefing",
    description:
      "Start each day with a personalised overview of your schedule, emails, and top priorities — generated by AI.",
  },
  {
    icon: MessageSquare,
    title: "Ask Sage",
    description:
      "Chat naturally to add tasks, reschedule meetings, and log expenses. Sage understands plain English.",
  },
  {
    icon: DollarSign,
    title: "Finance Tracker",
    description:
      "Monitor spending and savings. Upload any bill and Sage extracts the amount, due date, and category automatically.",
  },
  {
    icon: CheckSquare,
    title: "Smart Reminders",
    description:
      "Never miss a deadline. Tasks sync with Google Calendar in real time so every device stays up to date.",
  },
  {
    icon: Brain,
    title: "AI Rescheduling",
    description:
      "Tell Sage to move a meeting and it updates your task list and Google Calendar instantly — no manual edits.",
  },
  {
    icon: Receipt,
    title: "Bill Intelligence",
    description:
      "Upload a photo or PDF of any receipt and Sage reads it with Gemini Vision, creates the expense, and sets a reminder.",
  },
  {
    icon: Search,
    title: "Instant Search",
    description:
      "Search across all your tasks and expenses in real time from the navigation bar — results appear as you type.",
  },
  {
    icon: RefreshCcw,
    title: "Live Google Sync",
    description:
      "Events and tasks sync bidirectionally with Google Calendar so Sage always reflects your real schedule.",
  },
  {
    icon: Zap,
    title: "Lightning Fast",
    description:
      "Powered by Groq — the world's fastest LLM inference — so every AI response arrives in under a second.",
  },
];

const stats = [
  { value: "< 1s", label: "AI response time" },
  { value: "100%", label: "Google Calendar sync" },
  { value: "3-in-1", label: "Tasks · Finance · AI" },
  { value: "0 clicks", label: "to add from a photo" },
];

const footerLinks = {
  product: [
    { label: "Dashboard", href: "/dashboard" },
    { label: "Ask Sage", href: "/dashboard/command" },
    { label: "Finance", href: "/dashboard/finance" },
    { label: "Tasks", href: "/dashboard/tasks" },
  ],
  company: [
    { label: "About", href: "#" },
    { label: "Blog", href: "#" },
    { label: "Careers", href: "#" },
    { label: "Contact", href: "#" },
  ],
  legal: [
    { label: "Privacy Policy", href: "#" },
    { label: "Terms of Service", href: "#" },
    { label: "Cookie Policy", href: "#" },
  ],
};

/* ─────────────────────────────────────────── page ─ */
export default function LandingPage() {
  const [isLoggingIn, setIsLoggingIn] = useState(false);
  const { theme, setTheme } = useTheme();

  const handleLogin = async () => {
    setIsLoggingIn(true);
    try {
      const res = await getGoogleLoginUrl();
      if (res.auth_url) window.location.href = res.auth_url;
    } catch (e: any) {
      toast.error(e.message || "Failed to start login");
      setIsLoggingIn(false);
    }
  };

  return (
    <div className="min-h-screen bg-background text-foreground">

      {/* ── Navbar ──────────────────────────────────── */}
      <nav className="fixed top-0 inset-x-0 z-50 border-b border-border/60 bg-background/80 backdrop-blur-md">
        <div className="max-w-7xl mx-auto px-6 h-16 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-lg bg-primary flex items-center justify-center">
              <Sparkles className="w-5 h-5 text-primary-foreground" />
            </div>
            <span className="text-xl font-semibold">Sage</span>
          </Link>

          <div className="flex items-center gap-3">
            <Link href="/dashboard">
              <Button variant="ghost" size="sm" className="text-muted-foreground hover:text-foreground">
                Dashboard
              </Button>
            </Link>
            <Button
              variant="ghost"
              size="icon"
              onClick={() => setTheme(theme === "dark" ? "light" : "dark")}
              title="Toggle theme"
              className="text-muted-foreground hover:text-foreground"
            >
              {theme === "dark" ? <Sun className="w-4 h-4" /> : <Moon className="w-4 h-4" />}
            </Button>
            <Button size="sm" className="bg-primary text-primary-foreground hover:bg-primary/90" onClick={handleLogin} disabled={isLoggingIn}>
              {isLoggingIn ? <Loader2 className="w-4 h-4 mr-1.5 animate-spin" /> : null}
              Get Started
              {!isLoggingIn && <ArrowRight className="w-3.5 h-3.5 ml-1.5" />}
            </Button>
          </div>
        </div>
      </nav>

      {/* ── Hero ────────────────────────────────────── */}
      <section className="relative pt-36 pb-24 px-6 overflow-hidden">
        {/* ambient blobs */}
        <div className="pointer-events-none absolute -top-20 left-1/2 -translate-x-1/2 w-[700px] h-[400px] bg-primary/15 rounded-full blur-3xl" />
        <div className="pointer-events-none absolute top-40 right-10 w-64 h-64 bg-violet-500/10 rounded-full blur-3xl" />

        <div className="relative z-10 max-w-3xl mx-auto text-center">
          <motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5 }}>
            <span className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-primary/10 border border-primary/25 text-primary text-sm font-medium mb-6">
              <Sparkles className="w-3.5 h-3.5" />
              Your Intelligent Life Operating System
            </span>
          </motion.div>

          <motion.h1
            initial={{ opacity: 0, y: 16 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.1 }}
            className="text-5xl md:text-7xl font-bold tracking-tight mb-5 text-foreground"
          >
            Organize your life{" "}
            <span className="gradient-text">with Sage</span>
          </motion.h1>

          <motion.p
            initial={{ opacity: 0, y: 16 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.2 }}
            className="text-lg md:text-xl text-muted-foreground mb-10 max-w-2xl mx-auto leading-relaxed"
          >
            A comprehensive productivity dashboard that brings together your daily briefing,
            AI command center, finance tracker, and smart reminders in one elegant interface.
          </motion.p>

          <motion.div
            initial={{ opacity: 0, y: 16 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.3 }}
            className="flex flex-col sm:flex-row items-center justify-center gap-3"
          >
            <Button
              size="lg"
              className="bg-primary text-primary-foreground hover:bg-primary/90 glow-amber-sm px-8 gap-2"
              onClick={handleLogin}
              disabled={isLoggingIn}
            >
              {isLoggingIn ? <Loader2 className="w-4 h-4 animate-spin" /> : null}
              Open Dashboard
              {!isLoggingIn && <ArrowRight className="w-4 h-4" />}
            </Button>
            <Button size="lg" variant="outline" className="px-8 border-border hover:bg-secondary">
              Watch Demo
            </Button>
          </motion.div>
        </div>

        {/* Stats strip */}
        <motion.div
          initial={{ opacity: 0, y: 24 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, delay: 0.5 }}
          className="relative z-10 max-w-4xl mx-auto mt-20 grid grid-cols-2 md:grid-cols-4 gap-px rounded-2xl overflow-hidden border border-border bg-border"
        >
          {stats.map((s) => (
            <div key={s.label} className="bg-card px-6 py-5 text-center">
              <p className="text-2xl font-bold text-primary">{s.value}</p>
              <p className="text-xs text-muted-foreground mt-1">{s.label}</p>
            </div>
          ))}
        </motion.div>
      </section>

      {/* ── Features grid ───────────────────────────── */}
      <section className="py-24 px-6 border-t border-border">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-14">
            <motion.h2
              initial={{ opacity: 0, y: 12 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5 }}
              className="text-3xl md:text-4xl font-bold mb-3"
            >
              Everything you need, nothing you don&apos;t
            </motion.h2>
            <motion.p
              initial={{ opacity: 0, y: 12 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5, delay: 0.1 }}
              className="text-muted-foreground text-lg max-w-xl mx-auto"
            >
              Sage packs a full suite of intelligent productivity tools into a single beautiful interface.
            </motion.p>
          </div>

          <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-5">
            {features.map((f, i) => (
              <motion.div
                key={f.title}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.4, delay: i * 0.06 }}
                className="group flex flex-col gap-4 p-6 rounded-2xl bg-card border border-border hover:border-primary/40 hover:shadow-lg hover:shadow-primary/5 transition-all duration-300"
              >
                <div className="w-11 h-11 rounded-xl bg-primary/10 flex items-center justify-center shrink-0 group-hover:bg-primary/20 transition-colors">
                  <f.icon className="w-5 h-5 text-primary" />
                </div>
                <div>
                  <h3 className="font-semibold text-foreground mb-1.5">{f.title}</h3>
                  <p className="text-sm text-muted-foreground leading-relaxed">{f.description}</p>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ── CTA ─────────────────────────────────────── */}
      <section className="py-24 px-6 border-t border-border">
        <div className="max-w-3xl mx-auto text-center">
          <motion.div
            initial={{ opacity: 0, scale: 0.97 }}
            whileInView={{ opacity: 1, scale: 1 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5 }}
            className="relative p-12 rounded-3xl bg-card border border-border overflow-hidden"
          >
            {/* subtle gradient overlay */}
            <div className="pointer-events-none absolute inset-0 bg-gradient-to-br from-primary/8 via-transparent to-violet-500/5" />
            <div className="pointer-events-none absolute top-0 left-1/2 -translate-x-1/2 w-48 h-px bg-gradient-to-r from-transparent via-primary/60 to-transparent" />

            <div className="relative z-10">
              <span className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-primary/10 border border-primary/20 text-primary text-xs font-medium mb-6">
                <Sparkles className="w-3 h-3" /> Powered by Groq AI · Gemini Vision
              </span>
              <h2 className="text-3xl md:text-4xl font-bold mb-4">
                Ready to transform your productivity?
              </h2>
              <p className="text-muted-foreground mb-8 max-w-md mx-auto leading-relaxed">
                Let AI handle the chaos so you can focus on what actually matters.
              </p>
              <Button
                size="lg"
                className="bg-primary text-primary-foreground hover:bg-primary/90 glow-amber-sm px-10 gap-2"
                onClick={handleLogin}
                disabled={isLoggingIn}
              >
                {isLoggingIn ? <Loader2 className="w-4 h-4 animate-spin" /> : null}
                Get Started Free
                {!isLoggingIn && <ArrowRight className="w-4 h-4" />}
              </Button>
            </div>
          </motion.div>
        </div>
      </section>

      {/* ── Footer ──────────────────────────────────── */}
      <footer className="border-t border-border bg-card/40">
        <div className="max-w-6xl mx-auto px-6 pt-14 pb-8">
          {/* links grid */}
          <div className="grid grid-cols-1 md:grid-cols-5 gap-10 mb-12">
            {/* brand */}
            <div className="md:col-span-2 flex flex-col gap-4">
              <Link href="/" className="flex items-center gap-2 w-fit">
                <div className="w-8 h-8 rounded-lg bg-primary flex items-center justify-center">
                  <Sparkles className="w-5 h-5 text-primary-foreground" />
                </div>
                <span className="text-xl font-semibold">Sage</span>
              </Link>
              <p className="text-sm text-muted-foreground leading-relaxed max-w-xs">
                Your intelligent life operating system — bringing tasks, finance, and AI together in one elegant dashboard.
              </p>
              <div className="flex items-center gap-2 mt-1">
                {[
                  { Icon: Github, href: "https://github.com/prashantshirk/sage" },
                  { Icon: Twitter, href: "https://x.com/prashantshirke_" },
                  { Icon: Mail, href: "mailto:prashantshirke9324@gmail.com" }
                ].map(({ Icon, href }, i) => (
                  <a
                    key={i}
                    href={href}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="w-9 h-9 rounded-lg bg-secondary flex items-center justify-center text-muted-foreground hover:text-foreground hover:bg-secondary/80 transition-colors"
                  >
                    <Icon className="w-4 h-4" />
                  </a>
                ))}
              </div>
            </div>

            {/* Product */}
            <div>
              <h4 className="text-xs font-semibold text-foreground uppercase tracking-widest mb-4">Product</h4>
              <ul className="space-y-3">
                {footerLinks.product.map((l) => (
                  <li key={l.label}>
                    <Link href={l.href} className="text-sm text-muted-foreground hover:text-foreground transition-colors">
                      {l.label}
                    </Link>
                  </li>
                ))}
              </ul>
            </div>

            {/* Company */}
            <div>
              <h4 className="text-xs font-semibold text-foreground uppercase tracking-widest mb-4">Company</h4>
              <ul className="space-y-3">
                {footerLinks.company.map((l) => (
                  <li key={l.label}>
                    <Link href={l.href} className="text-sm text-muted-foreground hover:text-foreground transition-colors">
                      {l.label}
                    </Link>
                  </li>
                ))}
              </ul>
            </div>

            {/* Legal */}
            <div>
              <h4 className="text-xs font-semibold text-foreground uppercase tracking-widest mb-4">Legal</h4>
              <ul className="space-y-3">
                {footerLinks.legal.map((l) => (
                  <li key={l.label}>
                    <Link href={l.href} className="text-sm text-muted-foreground hover:text-foreground transition-colors">
                      {l.label}
                    </Link>
                  </li>
                ))}
              </ul>
            </div>
          </div>

          {/* bottom bar */}
          <div className="pt-6 border-t border-border flex flex-col md:flex-row items-center justify-between gap-3">
            <p className="text-sm text-muted-foreground">
              © {new Date().getFullYear()} Sage. Built with care for people who value their time.
            </p>
            <div className="flex items-center gap-1.5 text-sm text-muted-foreground">
              <span>Powered by</span>
              <span className="text-primary font-medium">Groq AI</span>
              <span className="text-border">·</span>
              <span className="text-primary font-medium">Gemini Vision</span>
              <span className="text-border">·</span>
              <span className="text-primary font-medium">Google Calendar</span>
            </div>
          </div>
        </div>
      </footer>

    </div>
  );
}
